[package]
name = "frontend"
version = "0.1.0"
authors = ["Yuri Iozzelli <y.iozzelli@gmail.com>"]

[dependencies]
stdweb = "0.3.0"
serde_derive = "1.0.27"
serde = "1.0.27"
serde_json = "1.0.9"

[dependencies.yew]
git = "https://github.com/DenisKolodin/yew.git"

