[package]
name = "feeder"
version = "0.1.0"
authors = ["Yuri Iozzelli <y.iozzelli@gmail.com>"]

[dependencies]
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"
rss = "1.2.1"
quicli = "0.1.2"
structopt = "0.1.7"
reqwest = "0.8.4"
rocket = "0.3.6"
rocket_codegen = "0.3.6"
r2d2 = "0.8.2"
r2d2-diesel = "1.0.0"
serde = "1.0.27"
serde_derive = "1.0.27"
rocket_cors = "0.2.1"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json"]
